### ISSUE TITLE
No prebuild binary for Darwin-arm64

### ISSUE THREAD

**Issue by chicco785** [kuuji/helm-external-val#4]
Despite I see the file in repo for v0.0.5, calling
```
helm plugin install --version v0.0.5 https://github.com/kuuji/helm-external-val
```
Results into:
```
No prebuild binary for Darwin-arm64
Failed to install helm-external-val
```

**Comment by kuuji** [comment]
~~We're not doing anything os or architecture specific so I think we could just build a binary for darwin-arm64 too.~~

NVM, I see what you mean, we do have a binary for that already. Time to dig into that script

**Comment by kuuji** [comment]
fixed in https://github.com/kuuji/helm-external-val/releases/tag/v0.0.6
